services:
  paperless-api:
    build: .
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/mydatabase"
      spring.datasource.username: "myuser"
      spring.datasource.password: "secret"
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
    depends_on:
        - 'postgres'
        - 'rabbitmq'
  paperless-ui:
    build: ./ui
    environment:
      - 'API_URL=http://paperless-api:8080'
    ports:
      - '80:80'
    volumes:
      - '.:/app'
    depends_on:
      - 'paperless-api'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
    depends_on:
      - 'postgres'
