version: "3.5"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: PaperlessREST/ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: PaperlessREST/Dockerfile
    depends_on:
      - 'postgres'
      - 'rabbitmq'
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/mydatabase"
      spring.datasource.username: "myuser"
      spring.datasource.password: "secret"
    ports:
      - "8088:8088"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
    depends_on:
      - 'postgres'
  minio:
    image: quay.io/minio/minio
    volumes:
      - miniostorage:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: PAPERLESS
      MINIO_ROOT_PASSWORD: PASSWORD
    ports:
      - 9090:9090           # this lets us access the minio ui on localhost:9090
      - 9000:9000           # this is the default port for minio
    command: server /data --console-address ":9090"
  ocr:
    build:
      dockerfile: paperlessOcr/Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - 'rabbitmq'
      - 'minio'
      - 'backend'
volumes:
  miniostorage:
